/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/todos": {
    /** Get the list of todos */
    get: operations["getTodos"];
  };
  "/api/create-todo": {
    /** add a new todo */
    post: operations["addTodo"];
  };
  "/api/delete-todo": {
    /** delete a todo */
    post: operations["deleteTodo"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Todo: {
      /** @description The todo to add to the list. */
      todo?: string;
    };
    TodoList: {
      /** @description The list of todos. */
      todos?: (string)[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** Get the list of todos */
  getTodos: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": components["schemas"]["TodoList"];
        };
      };
    };
  };
  /** add a new todo */
  addTodo: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Todo"];
      };
    };
    responses: {
      /** @description OK */
      200: never;
    };
  };
  /** delete a todo */
  deleteTodo: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Todo"];
      };
    };
    responses: {
      /** @description OK */
      200: never;
    };
  };
}
